export SAL_USE_VCLPLUGIN=gen
wmname LG3D
/home/quesada/.dropbox-dist/dropboxd&
/home/quesada/wuala/wualacmd&
dropbox start -i&
trayer --edge top --align right --width 10 --widthtype request --height 18 --transparent true&
/usr/bin/xflux -l 52.30, 13.25&
/usr/bin/workrave&
/usr/bin/lyx&
/usr/bin/konsole&
/usr/bin/firefox&
easystroke&
krunner&
xset b off&
# todo: if you use kdm/xdm/gdm etc you should edit the Sessions file below and
# add a line to your .initrc on your home ($HOME/.xinitrc)
#exec xmonad #already done on /etc/X11/Sessions/xmonad
